= FAQ
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:hide-uri-scheme:
:product: Gearchy

== Why do I need a GitHub account?

Brave Search currently supports goggles only when hosted on GitHub (public files and
gists) and GitLab (public files and snippets).

{product} integrates with GitHub Gists to access and permanently store your goggles.


== Why do I need a GitHub personal access token?

{product} is a client side only application and therefore can't implement the
OAuth's authentication flow securely since client ID and secret can't be stored
in a protected environment. Because of that, {product} uses the authentication
token authentication provided by the GitHub API.


== How to automatically submit updated goggles to Brave Search?

Once you have updated a goggle inside Geachy, you need to manually submit its URL to Brave Search on
https://search.brave.com/goggles/create to update it there as well.

However, this does not make much fun and therefore {product} can do it for you, if
you configure it to do so.

To automate the process, an API call needs to be made to the Brave Search API.
Unfortunately, this API comes with CORS restrictions and therefore can't be
accessed from a browser environment, in which a web application like {product} is
running.

A custom backend that acts as a proxy between {product} and the Brave Search API
is required for this. CORS restrictions don't apply here since the backend is
not running in a browser environment.

{product} comes with no API proxy configured by default.

But you can easily add the following proxy, which is provided by the {product} author:

[source]
----
https://app.gearchy.wolf.gdn/api/submit?url=%s
----

The source of the proxy is available at
https://github.com/devidw/gearchy/tree/main/api, feel free to fork it and
adjust it to your needs.

NOTE: The API proxy is not required for {product} to work. It's only purpose
is to automate the process of submitting goggles to Brave Search. If you don't
want an external service to handle your goggle URLs (including private ones), you
can either submit them manually or set up your own API proxy.

//
