import { defineStore } from 'pinia'
import { useGoggleStore } from './goggle'
import { availableHosts } from 'src/stores/hosts'
import type { GoggleFile, GoggleFilePreview } from 'src/types'

const goggleStore = useGoggleStore()

export const useGoggleFileStore = defineStore('goggleFile', {
  state: () => ({
    isLoading: false,
    error: undefined as Error | unknown | undefined,
    goggleFilePreviews: [] as GoggleFilePreview[],
    goggleFile: undefined as GoggleFile | undefined,
  }),

  getters: {
    host(state) {
      if (!state.goggleFile) return
      return availableHosts[state.goggleFile.host]
    },
    /**
     * Go through all available hosts and see if the optional pagination.hasNextPage is true
     */
    hasNextPage() {
      return Object.values(availableHosts).some(
        (host) => host.pagination?.hasNextPage,
      )
    },
  },

  actions: {
    /**
     * Retrieve all goggle files from all hosts
     */
    async list() {
      try {
        this.isLoading = true
        this.error = undefined
        const goggleFilePreviews = await Promise.all(
          Object.values(availableHosts).map((host) => host.list()),
        )
        this.goggleFilePreviews = goggleFilePreviews.flat()
      } catch (error) {
        this.error = error
      } finally {
        this.isLoading = false
      }
    },
    /**
     * Retrieve a given goggle file from a given host
     * And set it as the current goggle file
     */
    async retrieve(host: string, id: string) {
      try {
        // Only retrieve the goggle file if it is not already loaded in the current store
        if (
          this.goggleFile &&
          this.goggleFile.host === host &&
          this.goggleFile.id === id
        )
          return
        this.isLoading = true
        this.error = undefined
        this.goggleFile = await availableHosts[host].retrieve(id)
        goggleStore.parse(this.goggleFile)
      } catch (error) {
        this.error = error
      } finally {
        this.isLoading = false
      }
    },
    /**
     * Create a new goggle file under the given host
     * And set the current goggle file to the newly created one
     */
    async create(host: string) {
      try {
        this.isLoading = true
        this.error = undefined
        this.goggleFile = await availableHosts[host].create(
          'New Goggle',
          '! This is the default template for a new Goggle created with Gearchy\n! You can edit the Goggle on https://app.gearchy.wolf.gdn',
        )
        goggleStore.parse(this.goggleFile)
        this.resetPagination()
      } catch (error) {
        this.error = error
      } finally {
        this.isLoading = false
      }
    },
    /**
     * Update the host file with the current state
     * Content of the updated goggle file is generated by goggle store
     */
    async update() {
      try {
        if (!this.goggleFile || !this.host) throw new Error('No goggle file')
        this.isLoading = false
        this.error = undefined
        this.goggleFile.content = goggleStore.stringifiedGoggle
        await availableHosts[this.host.hostInfo.handle].update(this.goggleFile)
        this.resetPagination()
      } catch (error) {
        this.error = error
      } finally {
        this.isLoading = false
      }
    },
    /**
     * Update the host file with the current state
     */
    async delete() {
      try {
        if (!this.goggleFile || !this.host) throw new Error('No goggle file')
        this.isLoading = false
        this.error = undefined
        await availableHosts[this.host.hostInfo.handle].delete(
          this.goggleFile.id,
        )
        this.goggleFile = undefined
        goggleStore.goggle = undefined
        this.resetPagination()
      } catch (error) {
        this.error = error
      } finally {
        this.isLoading = false
      }
    },
    /**
     * Reset pagination for all hosts that implement the 'resetPagination' action
     */
    resetPagination() {
      this.goggleFilePreviews = []
      Object.values(availableHosts).forEach((host) => {
        if (typeof host.resetPagination === 'function') {
          host.resetPagination()
        }
      })
      this.list()
    },
  },
})
