version: '3.2'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace

  cypress:
    image: cypress/included:10.11.0
    depends_on:
      - dev
    environment:
      - CYPRESS_baseUrl=http://dev:9000
    working_dir: /workspace/app
    volumes:
      - ..:/workspace
